<div class="row">
    <div class="col-sm-6 col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="head-notif">
                <a role="button" data-toggle="collapse" href="#bloc-notif" aria-expanded="false" aria-controls="bloc-notif">
                    Notifications du jour : <?= count($this->arNotifs) ?>
                </a>
            </div>
            <ul class="list-group collapse <?= (count($this->arNotifs) === 0) ? '' : 'in' ?>" id="bloc-notif">
<?php foreach($this->arNotifs as $arNotif): ?>
                <li class="list-group-item list-group-item-danger">
                    <?= $arNotif['host'] ?> - <?= $arNotif['date'] ?> - <?= $arNotif['name'] ?> <?= $arNotif['status'] ?> (<?= $arNotif['value'] ?>) <br /> <?= $arNotif['human'] ?>
                </li>
<?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php foreach($this->arStatus as $sHostName => $arHostStatus) : 
    $sHtmlName = strtr($sHostName, ['.' => '-']);
    if ($sHostName !== '#General') : ?>
    <div class="col-sm-6 col-xs-12">
       <div class="panel <?= ($arHostStatus['#status'] === 'OK') ? 'panel-success' : 'panel-danger' ?>">
            <div class="panel-heading" role="tab" id="head-<?= $sHtmlName ?>">
                <a role="button" data-toggle="collapse" href="#bloc-<?= $sHtmlName ?>" aria-expanded="<?= ($arHostStatus['#status'] === 'OK') ? 'false' : 'true' ?>" aria-controls="bloc-<?= $sHtmlName ?>">
                    Machine : <?= $sHostName ?>
                </a>
            </div>
            <ul class="list-group collapse <?= ($arHostStatus['#status'] === 'OK') ? '' : 'in' ?>" id="bloc-<?= $sHtmlName ?>">
<?php foreach($arHostStatus as $sService => $arService): 
    if ($sService !== '#status'): ?>
                <li class="list-group-item <?= ($arService['status'] === 'OK') ? 'list-group-item-success' : ' list-group-item-danger' ?>">
                    <?= $sService ?> : <?= $arService['status'] ?> (<?= $arService['value'] ?>) - <?= $arService['human'] ?>
                </li>
<?php endif; endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; endforeach; ?>
</div>
<p class="text-center">
    Date de la vérification : <?= $this->arStatus['#General']['date'] ?><br />
    Date de l'affichage : <?= date('Y-m-d H:i:s'); ?>
</p>
